### ISSUE TITLE
Doesn't work on Arch Linux

### ISSUE THREAD

**Issue by hoschi** [neovim/python-client#105]
Sorry for the blurry titel, but I don't know how to describe it better. I have a running Arch Linux version and installed the packages neovim-git and python2-neovim as mentioned in the [install wiki page](https://github.com/neovim/neovim/wiki/Installing-Neovim#arch-linux). Neovim version is `NVIM 0.0.0-alpha+201504081227`.

I already described my problem at the [python2-neovim](https://aur.archlinux.org/packages/python2-neovim/) AUR package and here is a summary:
I have both python and python2 installed on my system. So I set `let g:python_host_prog='/usr/bin/python2'` in my `.nvimrc` to force it to python2. When I spawn a python REPL and load the neovim packages this works fine and I can control a nvim instance from python, see https://github.com/neovim/neovim/issues/2258 [or in the README of this github project]. But when installing YouCompleteMe, it prints still "YouCompleteMe unavailable: requires Vim compiled with Python 2.x support". When I try to do `:python print "hello"` in a nvim instance, I get `E117: Unknown function: provider#python#Call`. I also tried to upgrade the neovim python package with `pip2` which gives me version 0.0.32, but with the same outcome.

I symlinked `~/bin/python` to `/usr/bin/python2` so other commands use this as the python executable. I tried to remove it, in case it brakes something, but got the same problems without it.

**Comment by tarruda** [comment]
Did you set g:python_host_prog before any calls to `has('python')`? I recommend you to set it at the top of your nvimrc.

**Comment by hoschi** [comment]
I did, this is my `.nvimrc`
```
let g:python_host_prog='/usr/bin/python2'

call plug#begin('~/.nvim/plugged')

" Make sure you use single quotes
Plug 'Valloric/YouCompleteMe', { 'do': './install.sh' }

call plug#end()
```

This is the content of `.nvm`, I only installed vim-plug and YMC:
```
./autoload
./autoload/plug.vim
./.gitignore
./plugged
./plugged/YouCompleteMe
./plugged/YouCompleteMe/...
```

**Comment by tarruda** [comment]
Any other archlinux user experiencing this? @fwalch?

**Comment by fwalch** [comment]
I just tried with the `.nvimrc` posted above, worked fine.

**Comment by bfredl** [comment]
Not the same problem,  while nvim master + python2 `neovim` module works fine (without any configuration) the mere presence of an additional python3 `neovim` module (ie `python3 setup.py install --user`) borks nvim master completely (it claims `has('python')` but no python command works) However neovim/neovim#2208 seem to to the right thing under any combination of module availability, without needing to override `g:python_host_prog`. So it is really mostly a problem when testing `if_python3` and other PRs back and forth.

**Comment by hoschi** [comment]
I also tried turning the PC on and off again *just in case* ... but it didn't help :(

**Comment by fwalch** [comment]
Quite strange.. could it be that some environment variable (PYTHONPATH?) is the problem?

**Comment by hoschi** [comment]
`echo $PYTHONPATH` is empty/not set

**Comment by bfredl** [comment]
@hoschi It could be that `nvim` doesnt find it's runtime files (`E117: Unknown function: provider#python#Call`). For instance, does clipboard work (you need `xsel` package for this) or do you get similar error?

**Comment by bfredl** [comment]
What gives `:echo &rtp` with the nvimrc above?

**Comment by hoschi** [comment]
@bfredl I think you are right, `:help nvim-python` doesn't even work. When I try `"*p` in normal mode I get "clipboard: provider is not available. `xsel` is installed.

**Comment by hoschi** [comment]
`echo &rtp` gives:
```
/home/hoschi/.nvim,/home/hoschi/.nvim/plugged/YouCompleteMe/,/home/hoschi
/.nvim/plugged/vim-ctrlspace/,/usr/share/vim/vimfiles,/usr/share/vim/vim7
4,/usr/share/vim/vimfiles/after,/home/hoschi/.nvim/after
```
the pointers to `/usr/share/vim` are wrong I think?

**Comment by hoschi** [comment]
I have this line in my `.zshrc`:
```
export VIM=/usr/share/vim/
```
when I set this to `VIM=""` it works :)

**Comment by bfredl** [comment]
This is a bit confusing right now, but I think neovim/neovim#1927 will fix it (by reading `NVIM` but not `VIM`)

**Comment by hoschi** [comment]
Indeed, removing the line and spawning a new shell gives me still a value in `VIM` so I must set it to empty string.
