### ISSUE TITLE
has("gui_running") mappings have no effect

### ISSUE THREAD

**Issue by danihodovic** [neovim/python-client#106]
It seems like mappings declared in a block of
```
if has("gui_running")
  "mappings here
endif
```
do not apply for pynvim. It works for gvim however.

**Comment by tarruda** [comment]
`has('gui_running')` is only true if at least one RGB UI is connected when the expression is evaluated, which is not the case when sourcing vimrc. The easiest solution to the problem is add a nvim command-line flag that will force `has('gui_running')` to be true.

**Comment by bfredl** [comment]
IIUC  this is a generic neovim issue (for all guis) and not a python gui specific issue.
