### ISSUE TITLE
pynvim broken with Python 3?

### ISSUE THREAD

**Issue by fwalch** [neovim/python-client#114]
While running `pynvim` from Python 2 seems to work fine, the one from Python 3 only shows a blank screen. All dependencies should be installed (click, cairo, gobject).

**Comment by Pyrohh** [comment]
Do you have `python2-pip` installed as well? Not sure it makes a difference, but I was getting some bizarre failures when I had that and `python-pip` installed (more importantly, when I was using both to install Python packages).

I uninstalled `python2-pip`, removed the Python scripts in `~/.local/bin`, removed `~/.local/{lib,include}` and `~/.cache/pip`, then reinstalled all my python packages using `pip` and everything worked.

This is of course just guessing...

**Comment by fwalch** [comment]
I have it installed systemwide with the `python-neovim` package.. just to make sure there's no problem with anything `pip`-related, I moved the `.local` folder. Still the same problem (blank screen). Are you talking about pynvim from Python 3?

**Comment by Pyrohh** [comment]
> Still the same problem (blank screen). Are you talking about pynvim from Python 3?

Yes, I can reproduce... my mistake.

**Comment by Shougo** [comment]
I think it is not tested in Python3.

**Comment by tarruda** [comment]
I never tested pynvim with python 3, but I think you can run it with python 2 and still use python 3 as a plugin host for neovim

**Comment by fwalch** [comment]
What about disabling (not installing) `pynvim` for the Python 3 version? That would also avoid name clashes if both the python 2 and python 3 versions are available (currently has to be solved by packagers):

https://aur.archlinux.org/packages/py/python2-neovim/PKGBUILD
```
sed -i 's/pynvim/py2nvim/' setup.py neovim.egg-info/entry_points.txt
```
