### ISSUE TITLE
python-click dependency required?

### ISSUE THREAD

**Issue by fwalch** [neovim/python-client#115]
I can install and use the python-client (under Python 3) without problems, even without `click` installed. Is it really [required](https://github.com/neovim/python-client/blob/80516570b23b2d539040a1c7e8117adf7cd494f7/setup.py#L7)?

**Comment by Shougo** [comment]
https://github.com/neovim/python-client/blob/master/neovim/ui/cli.py

It is required for UI module...

**Comment by fwalch** [comment]
Yes, but the UI also requires gobject and Cairo, both of which are not in the setup file. Also, the UI doesn't work (#114).

**Comment by fwalch** [comment]
Created PR #116.

**Comment by Shougo** [comment]
#116  is good.
Is it closeable?

**Comment by fwalch** [comment]
@Shougo I added a reference to #116's commit message, so this issue will be auto-closed when #116 is merged.
