### ISSUE TITLE
attach() randomly prints an error in when using python3

### ISSUE THREAD

**Issue by BPaden** [neovim/python-client#124]
`nvim = attach("socket", path=os.environ["NVIM_LISTEN_ADDRESS"])` often (but not always) spits out `Exception ignored in:` with no other information.

It still seems to return a valid connection.

**Comment by teto** [comment]
I confirm this with python3 and it looks random, ie, you run the script on the same unchanged instance and the result will differ.
With neovim c75d5010b742db83462fc4508cf6dba455f79ca7

**Comment by justinmk** [comment]
Is this still an issue, with the latest versions of all components?
