### ISSUE TITLE
register an rplugin as compatible with both python2 and python3

### ISSUE THREAD

**Issue by bfredl** [neovim/python-client#125]
It would be great if there were a simple way to specify that an rplugin is able to run in either of the hosts. Futher on, it would be nice if the user could easly configure such a plugin to use a preferred version. For instance nvim-ipy is (soon) dual-version compatible, and  will (per default) execute user code in the same python version as the host version.

**Comment by bfredl** [comment]
From my (limited) experience, authors and users of "new-style" plugins prefer to just use python3 , so this is probably simply a non-issue.

**Comment by Shougo** [comment]
Yes, I think so too.  To create Python3 plugin is recommended.
Python2 will be deprecated after Ubuntu 16.04 is released.
It is default in Python3.
