### ISSUE TITLE
nvim does not throw IndexError when out of line in vim.current.buffer. 

### ISSUE THREAD

**Issue by SirVer** [neovim/python-client#128]
The line to test is `:py import vim; vim.current.buffer[100000]`. In regular vim you'll get:

~~~
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IndexError: line number out of range
~~~

In nvim no error is thrown. 

This was surfaced through [this UltiSnips test](https://github.com/SirVer/ultisnips/blob/master/test/test_ContextSnippets.py#L118) which is the last one failing with neovim in my current test branch, which is nice. 

On another note: I found out the hard way that nvim sets a bunch of options differently on startup (for example `smarttab`, `autoindent` and `backspace`) when started using `-u NONE` than vim. Is that intentional?

**Comment by BohrShaw** [comment]
> I found out the hard way that nvim sets a bunch of options differently on startup (for example smarttab, autoindent and backspace) when started using -u NONE than vim. Is that intentional?

See neovim/neovim#2676.

**Comment by tarruda** [comment]
@SirVer this needs to be fixed on the Neovim side, could you reopen on the main repository?

**Comment by justinmk** [comment]
It's because of https://github.com/neovim/neovim/pull/2846 which is a feature.

**Comment by tarruda** [comment]
> It's because of neovim/neovim#2846 which is a feature.

Even so, we might be able to emulate this vim behavior with a session hook on script_host.py, see how `vim.eval` is emulated without compromising the API for newer interfaces: https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/script_host.py#L173-L187

**Comment by justinmk** [comment]
Sure, that sounds good. Just wanted to point it out.

**Comment by SirVer** [comment]
Reopened as requested. I think @tarruda  is right that this should be emulated - after all the promise is for the neovim python client to provide a vim compatible python interface.

**Comment by idbrii** [comment]
The implemented solution to this issue still doesn't raise **IndexError**. It raises **NvimError**, but python iteration expects IndexError.

Take this example:
```
import vim

class VimBuffer:
    # A vim plugin might have a wrapper around the current Vim buffer.

    def __getitem__(self, idx):
        return vim.current.buffer[idx]


def dump(b):
    for line in b:
        print(line.upper())


# This works fine in both nvim and vim.
dump(vim.current.buffer)

# In nvim, the iteration fails with "pynvim.api.common.NvimError: Index out of bounds"
dump(VimBuffer())
```

Could solve it by changing `Buffer` in buffer.py to check for index errors:
```
    def __getitem__(self, idx: Union[int, slice]) -> Union[str, List[str]]:
        if not isinstance(idx, slice):
            i = adjust_index(idx)
            if i >= self.request('nvim_buf_line_count'):
                # Python iteration *expects* to request invalid lines and stops on IndexError.
                raise IndexError()
            return self.request('nvim_buf_get_lines', i, i + 1, True)[0]
        start = adjust_index(idx.start, 0)
        end = adjust_index(idx.stop, -1)
        return self.request('nvim_buf_get_lines', start, end, False)
```

Slices don't raise IndexErrors, so the second block doesn't need this check.


----

Workaround: Add `__iter__()` to VimBuffer so we use Buffer's specialized iteration instead of the fallback:

```python
class VimBuffer:
...

    def __iter__(self):
        return iter(vim.current.buffer)
```

This is an easy fix for vim plugins that also works in vim, but relies on plugin authors working around this incompatibility.

**Comment by justinmk** [comment]
PR welcome
