### ISSUE TITLE
Changing modes crashes the python client

### ISSUE THREAD

**Issue by oni-link** [neovim/python-client#131]
Changing modes crashes the python client in version 0.0.37:
```python
Traceback (most recent call last):
  File "/home/oni-link/pythonmodules/neovim/ui/ui_bridge.py", line 91, in apply_updates
    handler = getattr(self._ui, '_nvim_' + update[0])
AttributeError: 'GtkUI' object has no attribute '_nvim_mode_change'
```
Related to https://github.com/neovim/neovim/pull/2660

**Comment by justinmk** [comment]
Yes, all clients must be updated. After 0.1 I will present a "deprecation policy" so that this goes more smoothly. In the meantime this is a useful experiment to see how painful (or not) it is for clients to adapt to API breakage.
