### ISSUE TITLE
Client crashes when changing colorscheme

### ISSUE THREAD

**Issue by oni-link** [neovim/python-client#135]
python-client version 0.0.38

When changing the colorscheme with  `:colorscheme default`:

```
Traceback (most recent call last):
  File "neovim/ui/ui_bridge.py", line 91, in apply_updates
    handler = getattr(self._ui, '_nvim_' + update[0])
AttributeError: 'GtkUI' object has no attribute '_nvim_update_menu'
```

**Comment by vcunat** [comment]
And it seems that colorscheme setting in the config file is ignored.

**Comment by harish2704** [comment]
A temporary fix for now. 40cdf1c1a70e25a9e61d0379b40ce4aac84d4b94
> Do not crash the application due to un-implemented method.
> Instead throw a warning message and ignore the event

**Comment by bfredl** [comment]
see neovim/gui-client#2
