### ISSUE TITLE
documentation/help to start the gtk UI

### ISSUE THREAD

**Issue by llpamies** [neovim/python-client#144]
The main project README only talks about the python API. Is there any basic list of steps to start the GTK UI?

**Comment by tarruda** [comment]
I'm not sure if the gtk UI is working ATM, I haven't updated or used it in a long time.

As for the startup there's no documentation yet, but you can read the [main function](https://github.com/neovim/python-client/blob/master/neovim/ui/cli.py) to have an idea. Some months ago I wrote a [script](https://gist.github.com/tarruda/b67472898a7e4bd81572) to setup the necessary dependencies on pyenv.

**Comment by llpamies** [comment]
Thanks, I'll take a look.
