### ISSUE TITLE
redraw commands in python3 are buffers not strings

### ISSUE THREAD

**Issue by llpamies** [neovim/python-client#145]
This is a follow-up of #144. What happened is that in python3 the redraw instructions from nvim session are returned as byte buffers and not strings, and all the parsing expects strings. Besides that the GUI seems to work.

Is it supposed to work with python3? is anyone looking to fix this? I can take a look at it...

**Comment by bfredl** [comment]
In `ui/ui_bridge.py:on_notification` we need to decode the arguments.  Simplest might be to use `DecodeHook.walk(updates)` whenever IS_PYTHON3. (Per design, nvim only fully supports remote ui:s when `encoding=utf-8` so you can assume `utf-8` encoding, if it makes simpler).
