### ISSUE TITLE
VIm incompatibility: Appending at last line of buffer fails in neovim

### ISSUE THREAD

**Issue by tbabej** [neovim/python-client#155]
Beginning with a empty buffer, trying to add a new line under the first(empty) line, like this

    1| 
    2| test

by running

    :py import vim; vim.current.buffer.append("test", 1)

results in a "NvimError: Index out of bounds" in Neovim and has to be circumvented by calling

    :py import vim; vim.current.buffer.append("test")

This scenario works in just fine in regular Vim.

The workaround is to detect if you're appending at the last line of the buffer, however, that requires an additional msgrpc call to check the current buffer size, introducing a performance penalty.

**Comment by bfredl** [comment]
(sigh, why did they make it `append(obj, ind)` and not `insert(ind, obj)` as the python sequence protocol...)

Anyway, the range check in `buffer_set_line_slice` is to strict, it should be `inbounds(buf, start-1*include_start)` at least when `start>=0` .

**Comment by bfredl** [comment]
This is fixed in latest neovim master.
