### ISSUE TITLE
neovim python-client when using in a virtualenv

### ISSUE THREAD

**Issue by diefans** [neovim/python-client#16]
This is not a bug, but a documentation suggestion.

I tried out neovim with YouCompleteMe and all my python plugins (python-mode, virtualenv) enabled. Everything works fine and all vim plugins are loaded.

But when someone works within a virtualenv the thing is breaking. My solution to this is to install the python client into a virtualenv itself and setting ```PYTHONPATH=~/.virtualenvs/neovim/lib/python2.7/site-packages```

**Comment by sethwoodworth** [comment]
Are you appending that `PYTHONPATH` to the active `PYTHONPATH` when you've loaded a virtualenv?  I am going to need to solve this too, and I'm not sure how best to go about it.

**Comment by diefans** [comment]
its just in my ``.bashrc``, so ``neovim`` will be available in the system env and also in every activated virtualenv.

when there is a new nvim/neovim release, just ``workon neovim && pip install -U neovim && deactivate``

I always activate the project specific virtual env before running vim, I don't switch between virtual envs within an edit session (by vim plugins) - so I cannot tell you if there are any issues with that...

**Comment by xanderdunn** [comment]
@tarruda How did you solve this while using pyenv virtualenv?  Adding to my PYTHONPATH the location of site-packages that include the neovim package doesn't seem to be solving the problem for me.  When I have pyenv enabled for anything but the system package, neovim doesn't find Python.

**Comment by xanderdunn** [comment]
It looks like pointing neovim to my Homebrew Python installation did it: `let g:python_host_prog = '/usr/local/bin/python'`

**Comment by dylansm** [comment]
@xanderdunn Thank you for that—that did the trick for me after much difficulty.

**Comment by syclee** [comment]
@xanderdunn Worked for me too, cheers.

**Comment by tweekmonster** [comment]
I wrote up a wiki about setting up Neovim with Python: https://github.com/tweekmonster/nvim-python-doctor/wiki

There's a page dedicated to pyenv which could be helpful to new Neovim users.

**Comment by justinmk** [comment]
I think this was resolved by `:CheckHealth`, @tweekmonster LMK if not.
