### ISSUE TITLE
Calling a command using .command or .command_output turns off tab completion

### ISSUE THREAD

**Issue by TheZoq2** [neovim/python-client#162]
I have a simple plugin that calls :checktime at a fixed interval to force the autoread function to behave as I expect. However, when when a command is called using vim.command() and a tab completion is in progress, the tab completion gets 'cancelled' and the statusbar gets shown temporarily, even though I have laststatus=1.

This is the code for my plugin
```
import neovim
import time

@neovim.plugin
class Limit(object):
    def __init__(self, vim):
        self.vim = vim
        self.calls = 0

    @neovim.command('AutoreadLoop', range='', nargs='*', sync=False)
    def command_handler(self, args, range):
        while(True):
            self.vim.command("checktime")
            #self.vim.command_output("redraw")

            time.sleep(2);
```

I am using the latest neovim in the arch repositories

**Comment by bfredl** [comment]
Thanks for reporting this, though this is an issue with nvim itself and not the python-client. I think is basically same issue as neovim/neovim#3416 (python rplugins are implemented through job control)
