### ISSUE TITLE
multiple connections on embedded instance

### ISSUE THREAD

**Issue by timeyyy** [neovim/python-client#168]
i am able to connect to neovim with multiple connections in the python client using the socket method. I have been unable to reproduce this when i embed nevim into my app. 

(i just call the attach method with the same arguments and i think it embeds another instance). How do i get multiple connections my embedded neovim?

**Comment by bfredl** [comment]
you mean you try to connect to the same instance from different python processes? What OS is this on?

**Comment by tarruda** [comment]
@timeyyy what's the use case for this?

**Comment by timeyyy** [comment]
No the same python process, I'm on linux. I'm doing it for testing. I just thread my whole app and then connect to it (integration test), My current work around is to connect to a named pipe. 

This isn't a major issue.

**Comment by timeyyy** [comment]
Using nvim --headless gave me exactly what i want. An invisble neovim instance i can connect to multiple times.
