### ISSUE TITLE
.tar.gz files uploaded to PyPI is missing test/common.py

### ISSUE THREAD

**Issue by viccuad** [neovim/python-client#170]
The 0.1.2 tar.gz is missing test/common.py, and the tests can't be run.

(Maybe it is silly to say, but If you want to republish the tar.gz, please
bump the version instead of changing the file, to not mess with automatic tools
that harvest tar.gzs).

**Comment by viccuad** [comment]
After talking with @bfredl on gitter we have realized that the wrong tar.gzs are the ones published on PyPi (not the ones for download here in github):

Go to https://pypi.python.org/pypi/neovim/0.1.2, and download the one provided by PyPi (the one from the button top right: https://pypi.python.org/packages/source/n/neovim/neovim-0.1.2.tar.gz). That one doesn't have the common.py, and neither the 0.1.1, 0.1.0, etc have it.

(you can see all the Debian cached copies from PyPi here: https://pypi.debian.net/neovim).

**Comment by bfredl** [comment]
As we discussed on gitter, we should rename `common.py` to `test_common.py`
