### ISSUE TITLE
Child Nvim doesn't respond to any command.

### ISSUE THREAD

**Issue by DJMcMayhem** [neovim/python-client#174]
This code hangs on the nvim.command line.

```
import neovim

def getNvim():
    nvimPath = "/home/jmhjr/nvim"
    return neovim.attach("child", argv=[nvimPath, "nvim", "--embed"])

nvim = getNvim()
nvim.command("w /home/jmhjr/nvimOutput.txt")

print("finished!")
```

The same thing happens no matter what command I send to nvim, or if I connect in the python IDLE, rather than in a script.

**Comment by bfredl** [comment]
what could have happened is that nvim gets stuck at a message prompt, either at startup or when you `:write` (overwritten file?). if you execute some command instead of save, like `nohlsearch` does it still hang?

**Comment by DJMcMayhem** [comment]
Yeah, you hit the nail right on the head. It's working fine now. Thanks for your help!
