### ISSUE TITLE
README: a tad more documentation please

### ISSUE THREAD

**Issue by mhinz** [neovim/python-client#175]
Could you please add one or two sentences to each of the following points? Would probably help newbies or people that usually don't use Python. :)
1. How to run the tests?
2. How to make Neovim use `master` instead of whatever `pip` installed?

(Basically how to set up a proper environment for working at the Python client.)

**Comment by bfredl** [comment]
:+1: we should also have an overview of the new features relative vim's if_python and eventually set up sphinx docs or something

**Comment by bfredl** [comment]
Some improvements merged, but still some missing pieces like logging/troubleshooting.

**Comment by mhinz** [comment]
I like what I see so far! :+1:

**Comment by justinmk** [comment]
I guess https://github.com/neovim/python-client/commit/2db41a5a881fa899ae0108a0ba0ca7dd15bb2a67 covers this.
