### ISSUE TITLE
`UpdateRemotePlugins` crashes in UltiSnips without deoplete

### ISSUE THREAD

**Issue by Shougo** [neovim/python-client#202]
https://github.com/neovim/neovim/issues/4691

I have reproduced the problem in the latest neovim and neovim-python.
It seems neovim-python error.

Reproduce ways

* Load UltiSnips only (without deoplete)
* execute `:UpdateRemotePlugins`

**Comment by bfredl** [comment]
Thanks, but there is no need to duplicate the issue. (which I think is fixed) Let's keep discussion in neovim/neovim#4691. (IIRC github even supports closing issue in repo A by PR in repo B)
