### ISSUE TITLE
eval(mode(1)) hangs when a number is pending

### ISSUE THREAD

**Issue by DJMcMayhem** [neovim/python-client#205]
I should be able to use `eval(mode(1))` to see if a normal mode operation is pending or not. However, if that operation is a number, neovim hangs. For example, I typed this in my REPL:

```
import neovim
n = neovim.attach("child", argv=['/usr/bin/nvim', '--embed'])
n.input('2')
n.eval("mode(1)")
```

It never makes it past that line. I have also tested this with a non-embedded version. 

```
import neovim
n = neovim.attach("socket", path="/tmp/nvim")
n.input("2")
n.eval("mode(1)")
```

This hangs until I move my mouse over the nvim window, after which it responds with `n`. This seems to be clearing the pending number. For example, if I do

```
import neovim
n = neovim.attach("socket", path="/tmp/nvim")
n.input("2")
n.eval("mode(1)")
n.input("dw")
```

It deletes a single word, rather than 2 words like I would expect.

**Comment by bfredl** [comment]
This is a know limitation in nvim (not the python-client). Right now many wait-for-input states (like a incomplete normal command or pending-operator mode) are not yet proper states where events are processed (except for `input` and ui events, needed by an external ui), but it is planned they will be eventually. (I might look into this myself soon, to the extent it is needed for enhanced ui work)

**Comment by DJMcMayhem** [comment]
OK, thanks for letting me know. Do you know which states are like that, or where I can find a list?

**Comment by bfredl** [comment]
I don't think there is a list but the common cases should be: any incomplete command that shows the command to bottom right when `showcmd` is set  and "press ENTER" prompts doesn't support events right now. (command line modes like  `:` and `/` (and `i<C-R>=` I think...) support events)

**Comment by Dimfred** [comment]
There is probably still no progress on this from neovim side? Is there at least some api call to check whether we are in a pending input mode? I guess that would help me.

**Comment by justinmk** [comment]
> Is there at least some api call to check whether we are in a pending input mode?

[nvim_get_mode](https://neovim.io/doc/user/api.html#nvim_get_mode()) is the (imperfect but useful) answer to that.

**Comment by Dimfred** [comment]
I think I actually tried that, but the action was blocking too. While I am in operator pending / my socket hasn't closed I couldn't perform a second action like this with pynvim.

**Comment by justinmk** [comment]
> While I am in operator pending / my socket hasn't closed I couldn't perform a second action like this

check get_mode after sending user input (which is non-blocking), before doing anything else (which may block)
