### ISSUE TITLE
Code checking KeyError

### ISSUE THREAD

**Issue by zackhsi** [neovim/python-client#207]
<img width="635" alt="screen shot 2016-05-25 at 10 17 36 am" src="https://cloud.githubusercontent.com/assets/806101/15549563/efd7586a-2261-11e6-8db7-418a61124131.png">

This happens when I save changes. It doesn't happen every time, but it seems to be happening when I have open certain files or certain combinations of files.

I'm not sure if it's an issue here, or in the main neovim repo, or in the python-mode repo... Halp?

**Comment by bfredl** [comment]
This was likely not an error from the python-client but rather in a python plugin, but a bug in our error reporting made it seem so, fixed by #211.
