### ISSUE TITLE
Cannot use # in command name definition

### ISSUE THREAD

**Issue by aignas** [neovim/python-client#208]
Example on Python 3:

```python
import neovim

@neovim.plugin
class MyPlugin:
    _prefix = 'MyPlugin#'
    def __init__(self, vim):
        self.vim = vim

    @neovim.command(_prefix + 'myCommand', range='', nargs='*', sync=True)
    def my_command(self):
        pass
```

On a related note, `_prefix = 'MyPlugin"#"'` Makes the command to be defined as `MyPlugin`.

**Comment by bfredl** [comment]
but is it really a valid command name? `:command MyPlugin#myCommand` gives an error in nvim.

**Comment by aignas** [comment]
OK, I know what has confused me. I was reading the [omnisharp-vim README](https://github.com/OmniSharp/omnisharp-vim) and there was a line `vnoremap <leader><space> :call OmniSharp#GetCodeActions('visual')<cr>` and I got mixed up.

If I understand correctly, this is calling a function and my question then would be how to define such function?.

Thanks for pointing it out and sorry for the noise.
