### ISSUE TITLE
python_execute should show the original stacktrace or none at all

### ISSUE THREAD

**Issue by justinmk** [neovim/python-client#210]
When `python_execute` and friends run some plugin code, the stacktrace is misleading (and confusing):

http://paste.ubuntu.com/17093682/

```
Error while parsing, could not continue.                                                                                                
Erreur détectée en traitant function <SNR>100_RunPygd[3]..provider#python#Call :                                                        
ligne   18 :                                                                                                                            
UnboundLocalError("local variable 'tree' referenced before assignment",)                                                                
Traceback (most recent call last):                                                                                                      
  File "/home/teto/.local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 185, in handler                              
    rv = self._request_cb(name, args)                                                                                                   
  File "/home/teto/.local/lib/python2.7/site-packages/neovim/api/nvim.py", line 151, in filter_request_cb                               
    result = request_cb(self._from_nvim(name), args)                                                                                    
  File "/home/teto/.local/lib/python2.7/site-packages/neovim/plugin/host.py", line 74, in _on_request                                   
    rv = handler(*args)                                                                                                                 
  File "/home/teto/.local/lib/python2.7/site-packages/neovim/plugin/script_host.py", line 75, in python_execute                         
    exec(script, self.module.__dict__)                                                                                                  
  File "<string>", line 1, in <module>                                                                                                  
UnboundLocalError: local variable 'tree' referenced before assignment 
```

We should catch the exception and show the "inner" stacktrace, or at least hide the irrelevant python-client stacktrace.

**Comment by bfredl** [comment]
We should be able to change the error message to our liking using `ErrorResponse`. I will look into it.

**Comment by bfredl** [comment]
As a datapoint, vim doesn't show the python commandline either:
```
:py3 def somefun(): faail
:py3 somefun()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in somefun
NameError: name 'faail' is not defined
```

Not to say that we shouldn't try to do better than vim... I have a very faint memory of messing with python's code cache (used for showing lines in tracebacks) when hacking on [numba](https://github.com/numba/numba) a few years ago so it should be doable.

**Comment by bfredl** [comment]
The relevent logic seems to be here https://github.com/ipython/ipython/blob/master/IPython/core/compilerop.py
cpython apparently does not care about this usecase so IPython needs to monkeypatch the linecache. We should do the same.

**Comment by justinmk** [comment]
What about when Vim is running a python plugin, as opposed to command line one-off?

I didn't want to suggest anything risky like monkey patching. If it's not possible to get the inner trace, we can just hide the current, irrelevant one.

**Comment by bfredl** [comment]
Well there is no missing "inner" traceback, there is a single exception going all the way to the msgpack event loop and you can already see all the strackframes. What is missing is the actual line contents. IPython is used by huge userbase over many years, as it is the to-go solution for heavy interactive python work, so we can be sure their code has been thoroughly tested.

> What about when Vim is running a python plugin, as opposed to command line one-off?

If you mean code imported from a file then both vim and neovim is fine, as python can find the actual code in the source file. We still might want to shave off the python-client frames, though.

**Comment by justinmk** [comment]
closed by https://github.com/neovim/python-client/pull/211
