### ISSUE TITLE
Python rplugin blocks 

### ISSUE THREAD

**Issue by dzhou121** [neovim/python-client#212]
I'm trying to write a python rplugin and how can I do concurrent calls to the rplugin? For example, if I do a long running task in the rplugin, it will block the other calls from neovim. I've tried to start a new thread for each call, it seems not to execute at all.

**Comment by bfredl** [comment]
The correct solution is indeed to spawn a thread for long-running work, but note you cannot call API functions directly from a non-main thread. Use `nvim.async_call(somefun)` to call a function or a lambda on the main thread.

**Comment by dzhou121** [comment]
@bfredl That works now. Thanks for the tip.

**Comment by bfredl** [comment]
Nice, closing this then.
