### ISSUE TITLE
neovim.autocmd not working with "BufNewFile"

### ISSUE THREAD

**Issue by epwalsh** [neovim/python-client#213]
When I try to create an autocmd function with the BufNewFile event, the function never runs when opening a new file.

``` python
@neovim.autocmd('BufNewFile', pattern='*.*', eval='expand("<afile>")')
def insert_header(self, filename):
    ....
```

However, the same function works when used under different events, such as 'BufReadPre'.

**Comment by justinmk** [comment]
Are you sure the BufNewFile event is firing on the nvim side?
