### ISSUE TITLE
Erasing a line takes 80 _nvim_put(' ') calls

### ISSUE THREAD

**Issue by meatich** [neovim/python-client#215]
I was playing around with GTK Python GUI, but I am pretty sure it is either a Python client bug or Neovim bug.
Here is what happens. Suppose a screen 24 x 80. You are in insert mode on the second row, first column. If you press backspace now, the function _nvim_put will be called 80 times with a space as argument. Looks like a very inefficient way to erase a line.

**Comment by bfredl** [comment]
This is most certainly an issue of nvim itself. the python gui is passive with regards to controlling redrawing: all it does is send keyboard input and resize requests to nvim, and redraw events gets generated by nvim. python-gui just consumes them.

**Comment by bfredl** [comment]
Closed as this is not an issue in this repo (and it is not as bad as it seems, those 80 put:s will likely be put in the same rpc message)
