### ISSUE TITLE
No error shown when triggered in a callback

### ISSUE THREAD

**Issue by mhinz** [neovim/python-client#216]
Okay, here's the code, with the culprit line commented out:

```python
#!/usr/bin/env python3

import sys
import os
from neovim import attach

# WORKING:

def make_func(num):
    def func():
        num -= 1
        print(num)
    return func

try:
    make_func(5)()
except UnboundLocalError as e:
    print(e)

# NOT WORKING:

def setup_cb():
    nvim.command('call rpcnotify({}, "foo")'.format(nvim.channel_id))

def make_notification_cb(num):
    def notification_cb(msg, _args):
        num -= 1
        print(num)
        nvim.stop_loop()
    return notification_cb

notification_cb = make_notification_cb(5)

nvim = attach('child', argv=['nvim', '-u', 'NONE', '--embed'])
nvim.run_loop(None, notification_cb, setup_cb)
```

This code hangs. `num -= 1` is actually throwing an error. Change the code to see it:

```python
        try:
            num -= 1
        except UnboundLocalError as e:
            print(e)
```

It will output the same error as in the simple case, but still hang. The hang can be removed when the `print(num)` line gets removed as well.

UPDATE: For @Kjir, removing the `print(num)` does _not_ remove the hang. I guess this is where my Python-fu ends.

**Comment by Kjir** [comment]
Just in case they matter, here are some details of my environment

My python version:
```
$ python3 --version
Python 3.5.2
```
This is installed through `brew` on OS X El Capitan

Installed python packages:
```
$ pip3 freeze
greenlet==0.4.10
msgpack-python==0.4.7
neovim==0.1.9
```

**Comment by bfredl** [comment]
The issue is simple, the logic to pretty print errors in handlers is in the plugin host, and won't get invoked when running a standalone python script like nvr. It is easy to fix: add prints to stderr in `nvim.run_loop`. I will do a PR later.
