### ISSUE TITLE
Rpc not working with kivy

### ISSUE THREAD

**Issue by timeyyy** [neovim/python-client#218]
### The Bug
The following code runs fine if we comment the line with kivy in it
```python
from kivy.app import App # commenting this lets us spin up a neovim proceess and communicate with it
from distutils.spawn import find_executable
from neovim import attach

nvim_binary = find_executable('nvim')
args = [nvim_binary, '--embed']
nvim = attach('child', argv=args) # this call doesn't work properly with our kivy import..
```

With the import kivy line, the last line blocks. It's trying to do an rpc call.

Hitting `Ctrl +c ` when running as the main file 
```zsh
     nvim = attach('child', argv=args)
   File "/usr/local/lib/python3.5/dist-packages/neovim/__init__.py", line 94, in attach
     return Nvim.from_session(session).with_decode(decode)
   File "/usr/local/lib/python3.5/dist-packages/neovim/api/nvim.py", line 51, in from_session
     channel_id, metadata = session.request(b'vim_get_api_info')
   File "/usr/local/lib/python3.5/dist-packages/neovim/msgpack_rpc/session.py", line 94, in request
     raise IOError('EOF')
 OSError: EOF
```

when i run from another script.
```zsh
 Traceback (most recent call last):
   File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
     self._callback(*self._args)
   File "/usr/local/lib/python3.5/dist-packages/neovim/msgpack_rpc/event_loop/asyncio.py", line 62, in pipe_data_received
     if fd == sys.stderr.fileno():
 AttributeError: 'LogFile' object has no attribute 'fileno'
```
and when i hit `ctrl+c` again it will generate the first traceback above before quiting.

**Comment by timeyyy** [comment]
The behavior only happens when i am using the child method to connect

   _connect_child(argv): Use the argument vector `argv` to spawn an
          embedded Nvim that has it's stdin/stdout connected to the event loop.

Kivy prints some stuff on import that can be seen here.

Do i need to make kivy stop printing to stdio? 
Are there any other options?

**Comment by bfredl** [comment]
it appears we abuse `sys.stderr.fileno()` to get the stderr file number, which might not work because Kivy takes over `sys.stderr`. We should just use 2.

**Comment by bfredl** [comment]
@timeyyy please try #219

**Comment by timeyyy** [comment]
works
