### ISSUE TITLE
Predictable logfile name

### ISSUE THREAD

**Issue by blueyed** [neovim/python-client#222]
In https://github.com/neovim/python-client/blob/b8bb7c21f955fffb8c48ced31158772911604770/neovim/__init__.py#L101-L102 the value of `NVIM_PYTHON_LOG_FILE` is used to build the log file, but the python-client's PID gets appended.
That is unpredictable, e.g. when you just want to use `tail -F`, and you are likely to restart Neovim even.

You can use tricks like `logfile_*(om[1])` in zsh to use the most recent file, but then it won't be followed by `tail` when restarting Neovim.

I think there should be a way to just specify the logfile directly (without changing the source code).

**Comment by bfredl** [comment]
The reason for this was that that a nvim instance will likely launch multiple python-client instances, first both py2 and py3 and also both "legacy" and "rplugin" hosts (though, py2 rplugin hosts should hopefully be very rare, as the rplugin ecosystem has settled on python3). But I agree a deterministic scheme would be better, maybe `LOGFILE_py2_legacy` and `LOGFILE_py3_rplugin` where `LOGFILE` is the value of the env var. It might be possible to hack it in this repo only, but ideally nvim should tell the host the name of the host ("python" vs "legacy-python-provider")

**Comment by bfredl** [comment]
To immediately correct myself, nvim already tells python-client that it is a legacy scripthost through a "magic" plugin name, so this can be implemented properly in this repo only. I might look into it later today.
