### ISSUE TITLE
`err_write` function not working

### ISSUE THREAD

**Issue by fszymanski** [neovim/python-client#226]
I can not get the `err_write` function to work. The message does not show up. `out_write` works without a problem.

nvim: 0.1.5
python-client: 0.1.10

**Comment by bfredl** [comment]
Do you make sure to terminate the message with newline?

**Comment by fszymanski** [comment]
@bfredl you're absolutely right the `\n` is missing. Rookie mistake!
I need to take a break and go for a walk or something.
Thank you.
