### ISSUE TITLE
How to receive the event of cursor movement in python?

### ISSUE THREAD

**Issue by cancandan** [neovim/python-client#228]
I thought something like this should work no?

```
@neovim.autocmd('CursorMoved')
def on_cm():
    print 'moved'
```

I am trying this in python REPL btw

**Comment by justinmk** [comment]
The decorator isn't going to work in the REPL without additional setup. You need to create a rplugin as described in https://github.com/neovim/python-client#remote-new-style-plugins

this means, paste the sample code there in a file like `rplugin/python3/foo.py` or `rplugin/python/foo.py` on your nvim `'runtimepath'`. Then run `:UpdateRemotePlugins`, restart `nvim`, then check

    :au CursorMoved

you should see a `RPC_DEFINE_AUTOCMD_...` handler.

I confirmed that this works for CursorMoved.
