### ISSUE TITLE
command_output prepends a '\n' ?

### ISSUE THREAD

**Issue by teto** [neovim/python-client#245]
When running the following snippet with python 3 and client 0.1.13
```
import neovim
n = neovim.attach('child', argv=["/usr/bin/env", "nvim", "--embed"])
r = n.command_output('echo $MYVIMRC')
print("%r"% r)
'\n/home/teto/dotfiles/config/nvim/init.vim'
```
I would expect '/home/teto/dotfiles/config/nvim/init.vim' without the prepending '\n'. Is that normal behavior ?

**Comment by jamessan** [comment]
That's the implementation of `:echo` in (n)vim.  It's not specific to the python client.  From `:help :echo`:

```
							*:ec* *:echo*
:ec[ho] {expr1} ..	Echoes each {expr1}, with a space in between.  The
			first {expr1} starts on a new line.
```

**Comment by justinmk** [comment]
However I do think command_output (in nvim core) could (should) be changed to clean up the quirks of `:redir`.
