### ISSUE TITLE
Neovim Python client is not installed

### ISSUE THREAD

**Issue by arstum** [neovim/python-client#247]
Python 2 provider
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - WARNING: provider/pythonx: Could not load Python 2:
    python2 not found in search path or not executable.
    /usr/bin/python2.7 does not have the neovim module installed. See |provider-python|.
    /usr/bin/python2.6 does not have the neovim module installed. See |provider-python|.
    /usr/bin/python does not have the neovim module installed. See |provider-python|.
  - INFO: `g:python_host_prog` is not set.  Searching for python2.7 in the environment.
  - INFO: Executable: /usr/bin/python2.7
  - ERROR: Command error (4) /usr/bin/python2.7 -c import neovim; print(neovim.__file__): Traceback (most recent call last):  File "<string>", line 1, in <module>ImportError: No module named neovim
  - INFO: Python2 version: 2.7.10
  - INFO: python2.7-neovim version: unable to find nvim executable
  - ERROR: Neovim Python client is not installed.
    - SUGGESTIONS:
      - Error found was: unable to find nvim executable
      - Use the command `$ pip2 install neovim`
  - WARNING: Latest python2.7-neovim is NOT installed: 0.1.13

But problem still exist after run $ pip2 install neovim

Environment：
mac 10.11.6
brew install neovim
brew install python   （version is 2.7.10）
pip2 install neovim

**Comment by justinmk** [comment]
Did you run `sudo pip2` (that could be a problem on some versions of pip). Also try `pip2 install --user ...`
