### ISSUE TITLE
Updating the client automatically

### ISSUE THREAD

**Issue by odedlaz** [neovim/python-client#248]
Is there a way to automatically updated the client when neovim is updated?
I'm trying to figure out a way that's better than [this one](https://oded.ninja/2017/01/29/updating-neovim-python-client-automatically).

**Comment by justinmk** [comment]
If you use a plugin manager like [vim-plug](https://github.com/junegunn/vim-plug) you can do this:

    Plug '??', { 'do': 'pip install --upgrade neovim' }

(however I don't know what one would put in the `??` part, which normally points to a git repo containing a vim plugin. Maybe as vim-plug (or whatever plugin manager you use) a good way to "install arbitrary stuff without actually being a vim plugin". You _could_ just point the `??` to your personal dotfiles repo, but maybe there's a better way.

Also many OS package managers include the python modules as part of the package system, so when you do, for example, `apt-get update && apt-get upgrade`, nvim and the python modules will be upgraded (assuming you already installed them). E.g. debian and ubuntu and possibly others already have this: https://github.com/neovim/neovim/wiki/Installing-Neovim#debian

**Comment by odedlaz** [comment]
@justinmk, I'm not sure the above will work if you're running inside a virtualenv.

**Comment by justinmk** [comment]
I don't think we're prepared to do the gymnastics required to fiddle with people's virtualenv/pipenv/pyenv/...

Help would be very welcome. But the evidence thus far suggests python packaging is difficult to get right for the various versions and tools out there.

**Comment by justinmk** [comment]
You could try this plugin by @roxma: https://github.com/roxma/python-support.nvim

If it works well and someone wants to upstream it into nvim (and handle the inevitable bug reports), it would be welcome.
