### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by teto** [neovim/python-client#253]
When decoding message, there might be a proble m with encoding, for instance
`Cha\xc3\xaene` instead of `chaîne`.
`neovim.api.nvim.NvimError: b"Vim(echomsg):E730: Utilisation d'une Liste comme une Cha\xc3\xaene" `

**Comment by justinmk** [comment]
The `b"..."` indicates that it's a byte string, right? What decoding step are you referring to? According to python3 REPL:

```
>>> b"chaîne"
  File "<stdin>", line 1
SyntaxError: bytes can only contain ASCII literal characters.
>>> 
```

**Comment by teto** [comment]
Of course my bad.
