### ISSUE TITLE
Package stopped working after upgrade to Neovim 0.2

### ISSUE THREAD

**Issue by rubik** [neovim/python-client#257]
Immediately after the upgrade to Neovim 0.2 the Python client stopped working. Here's the error message:
```
$ nvim
function riv#init[4]..riv#load_conf[30]..provider#python#Call[9]..remote#host#Require[10]..provider#pythonx#Require, line 15
Vim(if):ch 1 was closed by the client
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named neovim
Failed to load python host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
Press ENTER or type command to continue 
```

But the package is installed and in fact I can import it manually:
```
$ python
Python 3.6.1 (default, Mar 27 2017, 00:27:06) 
[GCC 6.3.1 20170306] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import neovim
>>> neovim.VERSION
Version(major=0, minor=1, patch=13, prerelease='')
```

My Python 2 does not have neither Pip nor neovim installed, but this shouldn't be an issue because `echo has("python3")` returns 1 while the same command for Python 2 returns 0. So in theory Neovim shouldn't even try to execute Python 2.

Note: setting the suggested environment variables does not produce any logfile whatsoever (with debug enabled as shown in the README).

**Comment by justinmk** [comment]
What is `riv#load_conf` doing? We have automated tests testing python 2 and 3, so it can't be simply that it doesn't work.

**Comment by rubik** [comment]
I'm sorry, I thought I had disabled all plugins but I still had one, and it's a bug there. Sorry for wasting your time.
