### ISSUE TITLE
Unable to run UpdateRemotePlugins: No module named 'typing'

### ISSUE THREAD

**Issue by tatref** [neovim/python-client#259]
I'm trying to install https://github.com/autozimu/LanguageClient-neovim on a compiled neovim installation on Debian 8, Python3.4.

I installed the neovim python package via pip in a virtualenv (version 0.1.13)

I'm getting the following error:

```
Encountered ImportError loading plugin at /home/tatref/.config/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient: No module named 'typing'
Traceback (most recent call last):
  File "/home/tatref/neovim/venv/lib/python3.4/site-packages/neovim/plugin/host.py", line 131, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/home/tatref/neovim/venv/lib/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/home/tatref/neovim/venv/lib/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
ImportError: No module named 'typing'
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /home/tatref/.local/share/nvim/rplugin.vim
```

It seems that the `typing` module is new in Python 3.5, but the README states that Python from version 3.3 is supported.

Is this the case, or is this an issue with my installation?

Thanks!

**Comment by mhinz** [comment]
```
Encountered ImportError loading plugin at /home/tatref/.config/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient: No module named 'typing'
```

So, it's not [python-client](https://github.com/neovim/python-client) that needs Python 3.5, but LanguageClient-neovim.

Please create an issue in [their repository](https://github.com/autozimu/LanguageClient-neovim), since its README doesn't seem to mention the needed Python version.

**Comment by tatref** [comment]
Ok, I'll give it a shot.
Thanks for the quick answer!
