### ISSUE TITLE
window installation error:UnicodeDecodeError: 'utf-8' codec 

### ISSUE THREAD

**Issue by Averey** [neovim/python-client#260]
when i installed the neovim module in win10, I get the UnicodeDeocdeError:
![c0kwp j 8m yyis 6arpvq](https://cloud.githubusercontent.com/assets/3632515/26189459/6707eca8-3bd7-11e7-9a6c-8352f0f62725.png)

any idea to solve it?

**Comment by bfredl** [comment]
looks like pyuv problem. What python 3.X version do you use?

**Comment by Averey** [comment]
Python 3.6

**Comment by bfredl** [comment]
Looks like pyuv don't have wheels for 3.6 yet, hopefully it will be resolved soon: https://github.com/saghul/pyuv/issues/230

**Comment by Averey** [comment]
This error solved by chang python version to 3.5，thx @bfredl
