### ISSUE TITLE
Can't install on Android: unable to execute 'arm-linux-androideabi-clang'

### ISSUE THREAD

**Issue by kutsan** [neovim/python-client#267]
I can't install python client with `pip3 install neovim` on Android via Termux. What is the problem? What should I do? Is it a issue Termux itself or python-client?

Searchable transcript for Google and other places:

```
    unable to execute 'arm-linux-androideabi-clang': No such file or directory
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-0hgh1b_7/greenlet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-xvrwnuql-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-0hgh1b_7/greenlet/
```

![](https://i.imgur.com/u1S7YWA.png)

**Comment by bfredl** [comment]
Does termux ship with a distro package manager? Then you could try install python3-greenlet with it.

**Comment by kutsan** [comment]
There is no such package like `python3-greenlet ` on central package manager (Termux uses APT). Also can't install [this](https://pypi.python.org/pypi/greenlet) with pip3 (I don't know if it's what you referring to), it is ended up with same error.

**Comment by bfredl** [comment]
Does it use Debian packages? Or some unofficial port thereof?

**Comment by kutsan** [comment]
Yes they are unofficial ports, can't use Debian packages. They should be compiled specifically for Termux. https://github.com/termux/termux-packages

**Comment by bfredl** [comment]
Hmm, do you have gcc and python3-dev installed?

**Comment by kutsan** [comment]
Okay thanks, installing `clang` and `python-dev` packages via `apt install` solved the problem. You can close the issue as you wish.
