### ISSUE TITLE
Current visual block

### ISSUE THREAD

**Issue by povilasb** [neovim/python-client#268]
How do I get the current visual block?

I was looking at https://github.com/neovim/python-client/blob/master/neovim/api/nvim.py#L394, but it does not have anything related to visual blocks.
I've grepped - nothing.

Is it possible to do this over Neovim RPC api?

**Comment by justinmk** [comment]
> Is it possible to do this over Neovim RPC api?

@povilasb yes, you can use `nvim_eval("getpos(\"'<\")")` and `nvim_eval("getpos(\"'>\")")` to get the visual marks, then get the text using those positions.

https://github.com/neovim/python-client/pull/269 will make this easier I guess.

**Comment by povilasb** [comment]
Works like a charm! Thanks :)

**Comment by filyp** [comment]
< and > will get the last selection, not current.
For current v and . can be used.

Credit: https://stackoverflow.com/a/47051271/11756613
