### ISSUE TITLE
What is the best practice to initialize remote plugins and define mappings?

### ISSUE THREAD

**Issue by TomasTomecek** [neovim/python-client#279]
I am trying to write a new neovim plugin using this library. Since vim plugins are a new thing to me, I am struggling very much.

The thing which blocks me right now is to figure out the best way to define mappings: I want to define default keymaps and want users to be able to change them easily. So, what is the best practice for remote plugins to define mappings? Should I do it from python code once the plugin initialize, or should I do it from vim script, somewhere, somehow?

Any help is very much appreciated!

**Comment by bfredl** [comment]
Mappings should be defined in `plugin/myplugin.vim` . This way mappings will be visible without needing to actually load the python part, before first mapping actually is invoked. To enable mappings to be changed use indirection with `<Plug>(myplugin-someaction)`

**Comment by bfredl** [comment]
https://github.com/bfredl/nvim-ipy/blob/master/plugin/ipy.vim is an example. If mappings are too intrusive, they should be off by default.

**Comment by TomasTomecek** [comment]
Neat! This is so helpful. Thank you very much!
