### ISSUE TITLE
Question: Python plugin dependencies?

### ISSUE THREAD

**Issue by raghur** [neovim/python-client#281]
Question - if I write a python plugin and said plugin requires a dependency,
then what's the recommended way to set things up so that when the user does

```
Plug 'my/pythonplugin'
```

and installs it, then necessary dependencies are installed?

I guess I could have instructions for plugin managers in documentation, but
it would be much better if there was a way to set things up automatically.

Basically, in my case I have to run a `pip --user dependency` on installation.

**Comment by justinmk** [comment]
> I guess I could have instructions for plugin managers in documentation, 

You could supply a `requirements.txt` file, then users can do this:

     pip install -r requirements.txt

Hmm ... perhaps you're asking for a way that such a `requirements.txt` file could be auto-discovered, and then the user somehow gets a prompt. That might be interesting. But the UX would take some thought. E.g. to decide if the user needs to update, we need to ask `pip`. When do we do that, etc ...

**Comment by raghur** [comment]
>Hmm ... perhaps you're asking for a way that such a requirements.txt file could be auto-discovered, and then the user somehow gets a prompt. That might be interesting. But the UX would take some thought. E.g. to decide if the user needs to update, we need to ask pip. When do we do that, etc ...

Yes - something like a install hook that gets called when the plugin is first installed probably along with the path where the plugin is installed.

**Comment by meiralins** [comment]
You could also bundle the python dependencies in your project. Something similar to [deoplete-jedi](https://github.com/zchee/deoplete-jedi/tree/master/rplugin/python3/deoplete/vendored).

**Comment by raghur** [comment]
For now, I have a script file which runs `pip install --user -r requirements.txt` and then relying on the package manager to call it on install/update.
