### ISSUE TITLE
Stange behavior when setting vim variables

### ISSUE THREAD

**Issue by ipod825** [neovim/python-client#282]
I am trying to develop a plugin using this api.
But I found that I can only use `self.vim.vars['VariableName']= Value` one time.

To reproduce this, one can clone the [sample plugin](https://github.com/jacobsimpson/nvim-example-python-plugin). Then add the following two lines at [line 7](https://github.com/jacobsimpson/nvim-example-python-plugin/blob/0f99311d0e588cf083f008d2f1d2ba0a3b059104/rplugin/python/nvim-example-python-plugin.py#L7):
```python
        self.vim.vars['A'] = []
        self.vim.vars['B'] = []
```

Running `:UpdateRemotePlugins` gives:
`remote/host: python host registered plugins []`
which indicates the plugin is not correctly set.

On deleting the `B` (or `A`) line, leaving only one time of setting vim variable, running `:UpdateRemotePlugins` gives:
`remote/host: python host registered plugins ['nvim-example-python-plugin.py']`,
which indicates the plugin is correctly set.

This is also true by wrting:
`self.vim.request('nvim_set_var','A',[])`.
However, if put at other place other than `__init__` (or function called by `__init__`), it will work.

**Comment by bfredl** [comment]
The registration error will be fixed in neovim 0.3, in which the need of running `UpdateRemotePlugins` manually at all will be eliminated also.

Other than that, please avoid doing setup involving nvim in `__init__`, it will be called when the first python plugin is activated, not necessarily this plugin. Instead do it on demand when your plugin receives the first request from nvim.

**Comment by ipod825** [comment]
Hi @bfredl,
Is there any reason that we shouldn't do this? Also, why does it work if I just set only one variable.

**Comment by bfredl** [comment]
Short story: Because the infrastructure around `UpdateRemotePlugins` is a mess, or rather it was a good enough prototype implementation in 2014 when neovim was young and rplugins were few and trivial, but it should have been replaced with something more robust and flexible a long ago.

**Comment by ipod825** [comment]
Alright, thanks then.
