### ISSUE TITLE
Callback for jobstart

### ISSUE THREAD

**Issue by ipod825** [neovim/python-client#283]
Is there any way to handle the opts argument of nvim's jobstart function from python.
Something like:
```python
def handleLs(self, job_id, data, event):
     stuff

self.vim.call('jobstart', ['ls'], {'on_stdout': handlLs})
```
It's hard to tell from [this page](https://neovim.io/doc/user/job_control.html) how to achieve this in python.

**Comment by justinmk** [comment]
callbacks can't be serialized over RPC. At least not yet. https://github.com/neovim/neovim/issues/1898 tracks this idea, it's pie-in-the-sky for now though.

Instead, create a VimL callback and call `rpcrequest()` from your VimL callback.

**Comment by bfredl** [comment]
In this case it is better to just use pythons native io functions. If we were to deprecate pyuv, we could just expose the asyncio loop directly to rplugins...

**Comment by Shougo** [comment]
> In this case it is better to just use pythons native io functions. If we were to deprecate pyuv, we could just expose the asyncio loop directly to rplugins...

I think it is possible.  asyncio loop is available.

**Comment by justinmk** [comment]
Can someone leave a small code snippet here that achieves what @ipod825  requested ?

**Comment by ipod825** [comment]
Actually I ended using python's standard subprocess module.
```
subprocess.check_output('ls', shell=True).decode('utf-8')
```
At the end, I found if writing plugin in python, I don't really need to use nvim's jobstart
feature. subrpocess and threading modules can achieve what I want.

**Comment by ipod825** [comment]
To run asynchronously (though this then can't get the output back):
```python
thread.start_new_thread(lambda: subprocess.check_output('ls', shell=True).decode('utf-8'), ())
```

**Comment by bfredl** [comment]
@justinmk helper function is planned. I will fix windows support first though.
