### ISSUE TITLE
input keys and wait for change?

### ISSUE THREAD

**Issue by ipod825** [neovim/python-client#284]
What I need might be a "synchronous" input function.
My problem is that when I use `nvim.input` to feed keys to a neovim instance, the key will trigger some mapping which run some shell commands like 'mv foo bar'
In my test case, I would like to verify that `foo` becomes `bar` after the key is fed, so I have the following test code:
```python
vim.input('m')
assert 'bar' in subprocess.check_output('ls')
```
However, this won't work as the function that triggers 'mv foo bar' takes too long so that when `ls` is fired the file name hasn't been changed.

Did I miss something in the document that can achieve this goal? Or is it just not possible to achieve this in general?

**Comment by justinmk** [comment]
@ipod825 The usual way to achieve this is to have something like a `retry(timeout, fn)` test utility, so you could do something like:

    retry(1000, lambda: assert 'bar' in subprocess.check_output('ls'))
