### ISSUE TITLE
ImportError: No module named msgpack

### ISSUE THREAD

**Issue by PabloReszczynski** [neovim/python-client#292]
This started happening after I updated my pip packages, with both python 2.7 and 3.6.
What I tried:
- Uninstalling and installing neovim (version 0.2.0)
- Uninstalling and installing msgpack.

I'm on macOS sierra

**Comment by mhinz** [comment]
The package was renamed to `msgpack` only 3 days ago. This package still relies on `msgpack-python`. I did a PR for it here: https://github.com/neovim/python-client/pull/293

Maybe try reinstalling `msgpack-python`?

**Comment by mhinz** [comment]
The issue is mentioned here: https://pypi.python.org/pypi/msgpack/0.5.1

_When upgrading from msgpack-0.4 or earlier, don’t do pip install -U msgpack-python. Do pip uninstall msgpack-python; pip install msgpack instead._
