### ISSUE TITLE
msgpack 0.5.2 is not backward compatible, and is installed when doing a fresh install of neovim

### ISSUE THREAD

**Issue by antoine-wdg-rmz** [neovim/python-client#299]
As of today, doing `pip3 install neovim` on a fresh Ubuntu 16.04.3 installs version `0.5.2` of `msgpack-python`. This leads to a python exception when trying to `:UpdateRemotePlugins`.

Doing `pip3 install msgpack-python==0.5.1` fixes the issue. 
Minimal config is a fresh install of neovim with deoplete installed, let me know if you need any more info.

**Comment by nvllsvm** [comment]
Same here:

```
function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require, line 15
Vim(if):ch 1 was closed by the client
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/andrewr/Library/Python/3.6/lib/python/site-packages/neovim/__init__.py", line 70, in start_host
    session = stdio_session()
  File "/Users/andrewr/Library/Python/3.6/lib/python/site-packages/neovim/msgpack_rpc/__init__.py", line 37, in stdio_session
    return session('stdio')
  File "/Users/andrewr/Library/Python/3.6/lib/python/site-packages/neovim/msgpack_rpc/__init__.py", line 19, in session
    msgpack_stream = MsgpackStream(loop)
  File "/Users/andrewr/Library/Python/3.6/lib/python/site-packages/neovim/msgpack_rpc/msgpack_stream.py", line 23, in __init__
    self._packer = Packer(unicode_errors=unicode_errors_default)
  File "msgpack/_packer.pyx", line 136, in msgpack._packer.Packer.__init__
TypeError: expected bytes, str found
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
Press ENTER or type command to continue
```

**OS**: macOS 10.12.6
**Python**: 3.6.4
**NeoVim**: 0.2.2
**python-client**: 0.2.0

**Comment by justinmk** [comment]
We can pin the version for now.

**Comment by bfredl** [comment]
Hmm, so msgpack-python included backwards incompatible stuff in a patch level release. I wonder if that was a mistake, we should perhaps open an issue at https://github.com/msgpack/msgpack-python

More generally, we need to figure out the Right Thing for their 1.0.0 plans. Currently we have been using "surrogateescape" to mostly-transparently support roundtripping of invalid UTF-8, we might need to move this logic into our layers.

**Comment by bfredl** [comment]
The issue is that the default for `encoding` changed, we need to explicitly specify `utf-8`.

**Comment by justinmk** [comment]
Eventually we might be better off migrating to libmpack.

**Comment by methane** [comment]
I'm sorry for inconvenience.
I'm not familiar with neovim, but I recommend not using surrogateescape.
msgpack is cross-language serialization format like JSON.
And invalid UTF-8 is very bad for cross-language.
surrogateescape is Python only hack, not cross language.

If neovim should handle invalid UTF-8, bin type (which is for arbitrary byte sequence) is better type.

**Comment by bfredl** [comment]
@methane No one is exactly happy about invalid UTF-8, the point is treating it the least bad way. Nvim is mainly used to edit valid unicode text. Therefore most python3 plugins would want to represent edited file contents as the python3 `str` type (but they can opt-out to `bytes` if they want to). But nvim buffers are not guaranteed to contain valid UTF-8, and nvim will treat such a buffer as a mixture of unicode chars and invalid byte markers (which is logically consistent, as UTF-8 is self-synchronizing). We don't want python3 plugins to unconditionally crash in this situation. "surrogatespace" might be python specific "hack", but it is a python  _representation_ of the cross-language _ground truth_ "potentially invalid UTF-8" which python is far from the only language to deal with in a meaningful way.

If python-msgpack removes support for this, we need to either move encoding/decoding into our own wrapping layer, or switch to other library.

**Comment by methane** [comment]
I still dislike packing invalid UTF-8 as str data, but I admit "receive invalid UTF-8 and send it back"
scenario is pragmatic.
I'm considering reverting the deprecation for unicode_errors.  I'll remove only encoding option.
