### ISSUE TITLE
How do I write plugin tests which interact with neovim?

### ISSUE THREAD

**Issue by numirias** [neovim/python-client#314]
I'm trying to write tests for a plugin which require interaction with neovim. I want to write tests along the lines of:

```python
def test_buffer_saving(vim):
    my_plugin = MyPlugin(vim)
    vim.command("MyPluginSaveBuffer")
    assert my_plugin.saved_buffer == vim.current.buffer[:]
```
However, I'm unsure how to correctly set up the plugin with neovim in a testcase. I had a look at the setup at [`test/test_common.py`](https://github.com/neovim/python-client/blob/master/test/test_common.py) but I couldn't find an example where an actual plugin is loaded.

Spawning an embedded neovim instance works fine, but if I naively do something like...

```python
vim = neovim.attach('child', argv=...)
my_plugin = MyPlugin(vim)
```

... I would, for example, not register the plugin's `autocmd` handlers and probably miss a whole lot of initialization code.

Could you give me some hints how to correctly set up such tests?

**Comment by justinmk** [comment]
Maybe https://github.com/neovim/python-client/pull/317 helped? Full docs are at http://pynvim.readthedocs.io/en/latest/

**Comment by numirias** [comment]
Thanks. While I solved this for myself, I don't think the linked PR helps here because as far as I can see it doesn't address this issue's topic (writing tests for a plugin) at all.
