### ISSUE TITLE
Unable to attach

### ISSUE THREAD

**Issue by beigebrucewayne** [neovim/python-client#315]
Everything was working beautifully. Then I came back to a plugin I've been working on and tried to run `nvim = attach('socket', path='/tmp/nvim')` and the screenshot keeps occurring. I tried to uninstall / reinstall Neovim, but no luck. My `$NVIM_LISTEN_ADDRESS=/tmp/nvim nvim`, so I'm not sure what is going on. Seems to be a problem with asyncio, but don't get the issue since it's apart of the stdlib.

Python 3.6.4
Ipython 6.2.1

<img width="1067" alt="screen shot 2018-03-22 at 9 20 11 am" src="https://user-images.githubusercontent.com/25046261/37783507-e559662c-2db2-11e8-9de7-ff8d635334da.png">

**Comment by justinmk** [comment]
what version of the neovim (AKA pynvim) module?

**Comment by bfredl** [comment]
If do `:echo sockconnect('pipe', '/tmp/nvim`, {'rpc': v:true})` in another nvim instance, do you get non-zero return value?

**Comment by mhinz** [comment]
I just want to be really sure.. in the screenshot it says `FileNotFoundError`.

Does `/tmp/nvim` really exist? If so, maybe it's stale from a prior attempt when nvim was killed? (`:echo v:servername` in the nvim process should return `/tmp/nvim`.)

**Comment by beigebrucewayne** [comment]
It does exist. I tried removing it and re-running, same thing. If I run `:echo v:servername` I get back `/tmp/nvim nvim`

**Comment by beigebrucewayne** [comment]
Nevermind, I got it to work now. All I had to do was change the `$NVIM_LISTEN_ADDRESS=/tmp/nvim` instead of `$NVIM_LISTEN_ADDRESS=/tmp/nvim nvim`. Although, according to the README, the second option is *theoretically* the correct one.

**Comment by mhinz** [comment]
The README says `$ NVIM_LISTEN_ADDRESS=/tmp/nvim nvim` which denotes a shell command. It runs `nvim` but also sets the environment variable `NVIM_LISTEN_ADDRESS=/tmp/nvim` for that process and all its children.

**Comment by beigebrucewayne** [comment]
Got it, my bad. Thanks for the help.
