### ISSUE TITLE
Adding rplugin/python3 to sys.path?

### ISSUE THREAD

**Issue by tbodt** [neovim/python-client#319]
I'm writing a debugger plugin that provides a python API to other remote plugins that implement debuggers. I'd like the debuggers to just be able to import my code with an import statement, but `rplugin/python3` isn't in sys.path. I could add it, but the order of loading plugins is undefined, so that might not actually work.

Would there be any downsides to modifying the python remote client so it adds `rplugin/python(3)?` to sys.path?

**Comment by bfredl** [comment]
There is some prior art for this, deoplete is able to import sources from other rplugns, without unconditionally adding everything to `sys.path`, which I think we should avoid.

**Comment by tbodt** [comment]
OK, I think I have a solution for this.
