### ISSUE TITLE
Redirecting stdout/stderr for remote plugins

### ISSUE THREAD

**Issue by tbodt** [neovim/python-client#320]
It's inconvenient to have to pass around the `vim` object all over the place just so you can use it for logging.

**Comment by bfredl** [comment]
But `stdout`/`stderr` in the legacy interface doesn't do logging, it echoes messages to the user. For this explicit `nvim` I think is cleaner. For logging use the native interface:

    import logging
    logger = logging.getLogger(__name__)
    error, debug, info, warn = (logger.error, logger.debug, logger.info,
                                logger.warning)

**Comment by tbodt** [comment]
Oh, didn't know `logging` was set up.
