### ISSUE TITLE
Local variable setting

### ISSUE THREAD

**Issue by meijieru** [neovim/python-client#336]
We could set global variables easily by `self.vim.vars[{name}] = {values}`.
But for other scopes, it's could not do the same way.
I know `self.vim.command` could do the right thing, but why not a consistent way?

**Comment by justinmk** [comment]
use the buffer/window/tabpage objects:

http://pynvim.readthedocs.io/en/latest/api/buffer.html
http://pynvim.readthedocs.io/en/latest/api/window.html

**Comment by meijieru** [comment]
I have read the doc, but it does not clarify the problem.

**Comment by meijieru** [comment]
@justinmk Maybe I should use `buffer.set_var`?

**Comment by meijieru** [comment]
@justinmk The doc should generate docs for `Remote` class.
