### ISSUE TITLE
Tests fail on Linux with neovim from git

### ISSUE THREAD

**Issue by mcepl** [neovim/python-client#357]
When running
```
NVIM_CHILD_ARGV='["/usr/bin/nvim", "-u", "NONE", "--embed"]' pytest
```
(nvim is Linux/openSUSE binary build from the master, currently at neovim/neovim@0838b0025)

The result is a long list of warnings (``/usr/lib/python3.6/site-packages/neovim/msgpack_rpc/msgpack_stream.py:24: PendingDeprecationWarning: encoding is deprecated.``) and many errored tests (claiming ``E           neovim.api.nvim.NvimError: b'Vim(call):E117: Unknown function: BeforeEachTest'``)

[Full test log](https://github.com/neovim/python-client/files/2540290/pytest-log.txt) has been attached as well.

**Comment by justinmk** [comment]
could be related to https://github.com/neovim/python-client/issues/348 .

Or else the `@pytest.fixture` stuff in [conftest.py](https://github.com/neovim/python-client/blob/master/test/conftest.py) isn't getting applied, perhaps it requires a newer version of pytest?

**Comment by bfredl** [comment]
> PendingDeprecationWarning: encoding is deprecated.

Unfortunately ommiting `encoding` is not safe, as it defaults to the empty string and not "utf-8", and explicit "utf-8" is needed for `unicode_errors` to take effect

> E neovim.api.nvim.NvimError: b'Vim(call):E117: Unknown function: BeforeEachTest'

This was fixed on master. I'll get the import-from-thread fix merged and then do a release.
