### ISSUE TITLE
eval returns byte strings in python 3

### ISSUE THREAD

**Issue by dbarnett** [neovim/python-client#41]
python-client generally works in python 3, but returns byte strings from `eval()`. For instance,
```python
conn.eval("['x', '¬']")
```
returns
```python
[b'x', b'\xc2\xac']
```

Vim itself understands non-ASCII strings, so python-client should, too. This is not something that's trivial to work around in the calling code because recursive data structures can have strings deeply embedded. You'd have to recursively traverse the returned data structures and return an equivalent structure with all strings decoded.

**Comment by razvanc87** [comment]
Also methods decorated with `neovim.command` get their `args` as a list of `bytes`, not `str`. I don't think this is normal, is it?! `neovim.DecodeHooks` doesn't help either.

**Comment by Shougo** [comment]
Yes.  It is problem for me.

deoplete must decode the bytes like this:

```python
    @neovim.rpc_export('completion_begin')
    def completion_begin(self, context):
        # Encoding conversion
        encoding = self.vim.eval('&encoding')
        context = { k.decode(encoding) :
                    (v.decode(encoding) if isinstance(v, bytes) else v)
                    for k, v in context.items()}
```

**Comment by bfredl** [comment]
The client returns `str` now by default by all standard ways of initializing (vim plugin, rplugin, `attach()`).
