### ISSUE TITLE
Buffer gets/sets invalid indexes should raise IndexError

### ISSUE THREAD

**Issue by equalsraf** [neovim/python-client#49]
From #48. The following examples raise **IndexError** in Vim but not in Neovim

```python
vim.current.buffer[:] = ['line1']
vim.current.buffer[42] # returns 'line1'
```
```python
vim.current.buffer[33] # Invalid line index
```

I'm not sure what is the correct behaviour for all cases. Vim seems permissive about this when using slices but not indexes. From python it would be desirable to have IndexError but it seems the Neovim API functions dont raise an error for these cases.

**Comment by Tranquility** [comment]
I think this one (or something similar) is causing trouble with vim-orgmode. @tarruda do you have any idea what's causing this?

**Comment by tarruda** [comment]
> I think this one (or something similar) is causing trouble with vim-orgmode. @tarruda do you have any idea what's causing this?

Some changes may be necessary to api/buffer.c(buffer_get_line_slice) to fix this behavior

**Comment by bfredl** [comment]
indexing sholud be consistent with vim with latests versions of neovim and python-client
