### ISSUE TITLE
python-client imports from current working directory

### ISSUE THREAD

**Issue by btipling** [neovim/python-client#55]
Say I have a plugin at `~/.nvim/pythonx/neovim_thing.py` and it imports  `~/.nvim/pythonx/foo.py`. Assuming my current working directory is `~/dev/foo/`, if I start nvim and there happens to be a `~/dev/foo/foo.py` there this file is imported by my plugin instead of `~/.nvim/pythonx/foo.py` which breaks the plugin.

**Comment by justinmk** [comment]
Is https://github.com/neovim/python-client/blob/be6e96ee59f6101b20764eafe53bada6b8facb3e/neovim/plugin/host.py#L90 the place where this can be fixed?

**Comment by yagebu** [comment]
I only discovered this bug when running Nvim in a directory with a file `json.py` in it. In my setup, this is imported by YouCompleteMe. With neovim/neovim#3331, it correctly imports the system `json` module.

@justinmk in that line, only the plugin is loaded that was found 3 lines above. There it is actually made enforced that only the plugin path is searched (by giving it as an explicit argument to `imp.find_module`). There's only a problem if said plugin imports other Python modules. For these `sys.path` will be searched, which shouldn't contain the current working directory with the change in https://github.com/neovim/neovim/pull/3331/files#diff-56c8fc368678358892f215c76bd2178cR200. So my understanding is that neovim/neovim#3331 fixes this (at least it seems to do in my case :D )

**Comment by justinmk** [comment]
YCM uses the legacy python layer. Anything that uses python-client, without the legacy layer, I believe, will still have this issue.

**Comment by yagebu** [comment]
There seem to be two places where Nvim starts `python`. In `provider/pythonx.vim` to check if `python-neovim` is installed and in `remote/host.vim` to start remote python plugins. In both of them, the current working directory is removed from `sys.path` now. So I don't see how any python plugin that is spawned by Nvim would load anything from the current directory unless it changes the importing behaviour altogether.

Also the legacy layer (provided by `provider/script_host.py`) is basically just a remote nvim python plugin, isn't it? And placing a `logging.py` file in the current directory doesn't pose any problems for me.

**Comment by justinmk** [comment]
This project (python-client) may be used arbitrarily for any reason to communicate with an `nvim` instance.

**Comment by yagebu** [comment]
But in that case I would consider this a non-issue. If someone uses `python-neovim` as a library, they should make sure that it's imported correctly, just like any other library.

It might be desirable however to remove `""` from `sys.path` in `start_host()` as that is (just as its docstring states) basically an executable hidden in a function and should hence not have any import issues depending on where `python` is run from.

**Comment by bfredl** [comment]
this should be working as intended now.
