### ISSUE TITLE
Using vim.eval to eval a variable value will fail the first time.

### ISSUE THREAD

**Issue by btipling** [neovim/python-client#69]
Steps to reproduce:

Create a plugin like so and name it `foo.py` or whatever you want to call it:

```
import neovim

@neovim.plugin
class Foo(object):
    def __init__(self, vim):
        self.vim = vim

    @neovim.command('TestFoo', sync=True, nargs=1)
    def foo_test(self, args):
        foovar = self.vim.eval(args[0])
        self.vim.command("echom 'result %s'" % foovar)
```

Update plugins:

```
nvim -c 'UpdateRemotePlugins' -c 'q'
```

Start neovim.

```
$  nvim
```

Set a variable on the input prompt:

```
:let foo = 'bar'
```

Verify it is set:

```
:echom foo
```
That should echo "bar" to :messages

Now try the plugin:

```
:TestFoo foo
```

This will show an error like so:

```
Error detected while processing function remote#define#CommandBootstrap:
line    5:
NvimError('Vim:E121: Undefined variable: foo',)
```

Try it again.

```
:TestFoo foo
```

See that it works:

```
result bar
```

I have followed vim_eval.c all the way down to `eval7` and `find_var` with lldb and it's definitely trying to find the variable, but it just doesn't find it, it's not where it's looking. It creates a hash from the variable name, which looks like it's just an integer and sees if it's in a hash table and it isn't there.  nvim can find it from the input prompt, but the plugin can't until after the first failure.

**Comment by bfredl** [comment]
right, always use scopes with `eval()`
