### ISSUE TITLE
unhelpful error message on `UpdateRemotePlugins`

### ISSUE THREAD

**Issue by bfredl** [neovim/python-client#73]
Steps to reproduce:
     1. Add some error to an existing (remote) python plugin that would stop it from load (syntax error, importing misspelled module etc)
     2. run `:UpdateRemotePlugins`
![neovim](https://cloud.githubusercontent.com/assets/1363104/5519911/99222e84-8968-11e4-8f30-541495287d77.png)
This message make it sound like the python _host_ is broken, which is very confusing. It would be better perhaps if the python exception could be printed, then it would be much quicker to find and fix the actual problem. (Those `Missing :endif` are also wierd, since `endif` is definitely not missing,  but I suppose it is some internal vimscript exception handling glitch)

**Comment by bfredl** [comment]
Also, if `rtp` contains two remote python plugins, and the first one is ok, but the 2nd one has e.g. a syntax error, this error is just silently ignored. `nvimrc-rplugin` then gets this contents:
```
cat .vim/.nvimrc-rplugin\~ 
" python plugins
call remote#host#RegisterPlugin('python', '/home/bjorn/dev/nvim-ipy/rplugin/python/nvim_ipy.py', [
      \ {'sync': 0, 'name': 'IPyComplete', 'type': 'function', 'opts': {}},
      \ {'sync': 0, 'name': 'IPyConnect', 'type': 'function', 'opts': {}},
      \ {'sync': 0, 'name': 'IPyRun', 'type': 'function', 'opts': {}},
      \ {'sync': 0, 'name': 'IPyInterrupt', 'type': 'function', 'opts': {}},
      \ {'sync': 0, 'name': 'IPyObjInfo', 'type': 'function', 'opts': {}},
      \ {'sync': 0, 'name': 'IPyTerminate', 'type': 'function', 'opts': {}},
     \ ])
call remote#host#RegisterPlugin('python', '/home/bjorn/dev/taskmngr/rplugin/python/nvim_taskmngr.py', [
      \ {'sync': 0, 'name': 'IPyComplete', 'type': 'function', 'opts': {}},
      \ {'sync': 0, 'name': 'IPyConnect', 'type': 'function', 'opts': {}},
      \ {'sync': 0, 'name': 'IPyRun', 'type': 'function', 'opts': {}},
      \ {'sync': 0, 'name': 'IPyInterrupt', 'type': 'function', 'opts': {}},
      \ {'sync': 0, 'name': 'IPyObjInfo', 'type': 'function', 'opts': {}},
      \ {'sync': 0, 'name': 'IPyTerminate', 'type': 'function', 'opts': {}},
     \ ])
```
it seems that the secound plugin `nvim_taskmngr.py`, which has a syntax error, just gets registered the same methods as the first one!

**Comment by bfredl** [comment]
Seems still an issue.

**Comment by tarruda** [comment]
After neovim/neovim#2208 I will move the python code registration to it's own repository, and will have a look at improving this message.

**Comment by tarruda** [comment]
I've added a small improvement to the error message: https://github.com/tarruda/neovim/commit/54bd3843384af34c895942acb32ca3996d5cb614

There are still problems with the loading infrastructure, but I will have to deal with those later

**Comment by bfredl** [comment]
nvimrc-rplugin don't get wrong contents, but now error is just silently ignored. Rather than hiding errors in logs, this is true for errors on method calls in rplugins as well, wouldn't it be better to just echo the traceback? One might say "it is not friendly to the (plugin) enduser to throw a big, incomprehensible traceback in their face" but this a lot better than what we do now, i e either later showing another equally annoing vimscript error (but completely useless to the plugin developer) or (much worse) just letting the rplugin silently misbehave, and thus forcing the plugin _user_ to mess with debug settings and logfiles to just have anything to report to the plugin developer.
