### ISSUE TITLE
Glitches for 'cursorline' on Gtk UI

### ISSUE THREAD

**Issue by fmoralesc** [neovim/python-client#75]
Just found some glitches when trying out pynvim's Gtk UI (very cool job btw, @tarruda). See the cursorline in the bottom split:

![captura de pantalla de 2015-01-15 11 08 45](https://cloud.githubusercontent.com/assets/221465/5758799/2eeba6ec-9ca7-11e4-8cd6-3cdb6ffa8d2a.png)
![captura de pantalla de 2015-01-15 11 08 34](https://cloud.githubusercontent.com/assets/221465/5758800/2ef103f8-9ca7-11e4-9887-4d6fa45cafb3.png)

**Comment by tarruda** [comment]
My guess is that this is caused by the `eol_clear` command, which can leave a row of pixels from the previous highlight.

Currently I'm working on integrating libtickit UI to neovim core, I will investigate more when I start working on the neovim gtk widget.

Thanks for reporting.

**Comment by bfredl** [comment]
I don't know if this is still an issue (I cannot reproduce), but if it is, reopen in `neovim/python-gui`
