### ISSUE TITLE
test_vim.test_strwidth fails with assertionerror (63 != 44)

### ISSUE THREAD

**Issue by stevendlander** [neovim/python-client#78]
While trying to author some test scripts for ui/screen.py, the test script reported that test_vim.test_strwidth throws an assertionerror.  [Error output uploaded here.](https://drive.google.com/file/d/0B6m-m7RTR-ZIdEhrRG04M1BscFk/view?usp=sharing)

Environment:
Hardware: C720 Acer Chromebook
OS: Debian Sid running as chroot
Python Version: 2.7

Please advise if you need any additional info.

**Comment by tarruda** [comment]
This could be due to decoding error, what happens if you do `set encoding=utf-8` before the test?

**Comment by stevendlander** [comment]
Looks like this is happening because my terminal encoding was set to POSIX.

I ran `export LC_ALL=C.UTF-8` followed by `export LANG=$LC_ALL` and the tests completed without problem.

**Comment by tarruda** [comment]
> Looks like this is happening because my terminal encoding was set to POSIX.

POSIX can't decode those asian characters used in the test, illegal bytes are displayed as `<xx>`, thats why you get a higher strwidth
