### ISSUE TITLE
"No package 'libffi' found" error during pip install

### ISSUE THREAD

**Issue by DavidGamba** [neovim/python-client#79]
In ubuntu had to run:
sudo apt-get install libffi-dev python-dev

Let me know if you think this should be added to the README to add a PR or if not, people can just search the closed issues for info on it.

**Comment by tarruda** [comment]
Hmm I think its best to simply remove  cffi dependency, the TUI module is not official yet and also not a requirement for the library. Could you open a PR?

**Comment by cheif** [comment]
Same problem here.

**Comment by tarruda** [comment]
Should be fixed on latest version
