### ISSUE TITLE
Window objects cannot be compared to each other

### ISSUE THREAD

**Issue by ZyX-I** [neovim/python-client#85]
In Vim I would expect the following print `True`:

    python import vim; print vim.windows[int(vim.eval('winnr()')) - 1] is vim.current.window

. But in NeoVim I can neither use the above code nor compare `window.number` attribute. This attribute is present at least since vim-7.0.112. Tabpage objects are missing this attribute as well.

**Comment by bfredl** [comment]
fixed except for the number part (#87)
