### ISSUE TITLE
The `reverse` attr actually means `swap`

### ISSUE THREAD

**Issue by coolwanglu** [neovim/python-client#90]
On [this line](https://github.com/neovim/python-client/blob/master/neovim/ui/gtk_ui.py#L474), the `reverse` attr is interpreted as inverting the rgb color, while I found that it should be `swapping fg and bg` despite of its confusing name:

- [Wikipedia](http://en.wikipedia.org/wiki/ANSI_escape_code) (Search for `inverse or reverse`)
- [Vim](https://github.com/coolwanglu/vim.js/blob/master/src/gui_gtk_x11.c#L3755) 

Not sure if anything should be changed in neovim.

**Comment by tarruda** [comment]
:+1: 

I will fix after neovim/neovim#1820 is merged

**Comment by coolwanglu** [comment]
Need just a few lines :)
See #91
