### ISSUE TITLE
There is no way to paste clipboard content

### ISSUE THREAD

**Issue by sirex** [neovim/python-client#92]
Gvim has `+` and `*` for clipboard content. But `pynvim` does not have these registers and it means, that there is no way to insert content into `pynvim` from clipboard.

**Comment by bfredl** [comment]
On X11 platforms `xsel` (or `xclip`) is required for clipboard function, do you have any of these? (BTW clipboard is handled in core neovim and is not dependent On `pynvim`)

**Comment by sirex** [comment]
Thanks, after `sudo apt install xsel` these registers started to work, but `:registers` still don't show `+´ and `*`. Strange.

Another strange thing is that `vim` does not have these registers, but `gvim` has and it works without `xsel` or `xclip`.

And if clipboard functionality depends on external executables does not look like `neo`, it smells like `oldish` thing.

**Comment by justinmk** [comment]
> :registers still don't show +´ and*`. Strange.

It's a known issue, already in the issue tracker. 

> but gvim has and it works without xsel or xclip.

gvim links to X libraries. Unlike gvim, Neovim does not have a compilation-time dependency on X. Vim (with clipboard support) does. Neovim also supports user-extension of clipboard support.

**Comment by tarruda** [comment]
> And if clipboard functionality depends on external executables does not look like neo, it smells like oldish thing.

Vim depends on external executables for:

- spawning processes
- completing filenames
- generating diffs

Neovim is simply externalizing more things than Vim, and simplifying code as a consequence. And its not like Vim doesn't depend on anything. As @justinmk explained, if you don't have the `libx11-dev` package when compiling, Vim won't have clipboard. From the user perspective, adding clipboard to Neovim is a matter of doing `apt-get install xsel` vs `apt-get install libx11-dev` before compiling Vim
