### ISSUE TITLE
CTRL-^ and CTRL-6 does not work in pynvim

### ISSUE THREAD

**Issue by sirex** [neovim/python-client#94]
`CTRL-^` and `CTRL-6` should open alternate file (`#`), but those mappings simply does not work in `pynvim`.

**Comment by tarruda** [comment]
I just added the translation for those keys(version 0.0.30), I will publish to pypi when neovim/neovim#2182 is merged later

**Comment by tarruda** [comment]
Should be fixed on pypi now. Can you verify with `pip install --upgrade neovim`? You also need to update Neovim

**Comment by sirex** [comment]
I'm using neovim from PPA, so I will wait for update from there.
