### ISSUE TITLE
Incorrect rendering in pynvim with Terminus 12 font

### ISSUE THREAD

**Issue by sirex** [neovim/python-client#95]
I [changed font](https://github.com/neovim/python-client/blob/master/neovim/ui/gtk_ui.py#L70-L71) from Monospace 13 to Terminus 12, and after that, pynvim rendering started to produce some artefacts. Here is how it looks:

![shot-002](https://cloud.githubusercontent.com/assets/297583/6747708/fde51f8a-cee5-11e4-8e24-fea1d16a95f2.png)

I guess this is related to different font character square shape.

I know, that there are plans to rewrite GTK UI rendering to C, but still, maybe this will be useful to know about this bug.

**Comment by tarruda** [comment]
this is also a problem with OSX default monospace font. Not sure if its possible to fix this with pango configuration parameter or if I will have to draw each character individually to have full control over the space taken by each cell
