### ISSUE TITLE
Change cursor shape in insert mode

### ISSUE THREAD

**Issue by oakes** [neovim/python-client#96]
I haven't built this client in a while, but I assume it always uses a block-style cursor as in terminals. It would be nice to use a line-style cursor when in insert mode, similar to MacVim and gVim. This client uses a GtkDrawingArea, and [my own Neovim GUI](https://github.com/oakes/SolidOak) uses a VteTerminal. Would this be achievable if we had Neovim control a GtkTextView instead, or is there another way to do it?

**Comment by tarruda** [comment]
Its already done: https://github.com/neovim/python-client/blob/master/neovim/ui/gtk_ui.py#L468-L471

**Comment by oakes** [comment]
Interesting, maybe I should use this approach myself then. Are you able to paste from the system clipboard?

**Comment by tarruda** [comment]
> Interesting, maybe I should use this approach myself then

If you can wait a week or two, I plan to refactor all gtk-specific bits to a native gtk widget written in C, which you can probably use in solidoak.

> Are you able to paste from the system clipboard?

Currently this is handled by the clipboard provider script which relies on `xsel`/`xclip`/`pbcopy`/`pbpaste`, though we may refactor it so the UI can provide its own implementation(It will certainly be useful for a GUI connected to nvim in a remote server via ssh)

**Comment by oakes** [comment]
> If you can wait a week or two, I plan to refactor all gtk-specific bits to a native gtk widget written in C, which you can probably use in solidoak.

Great, I'll keep an eye out for it.
