### ISSUE TITLE
'Buffer' object has no attribute '_handle'

### ISSUE THREAD

**Issue by rgrinberg** [neovim/python-client#98]
Running [merlin](https://github.com/the-lambda-church/merlin) in neovim I get the following error:

```
Vim(return):AttributeError("'Buffer' object has no attribute '_handle'",)
```

Is this a known bug? Anything that can be easily fixed?

**Comment by mseri** [comment]
I am still getting this error with the latest version of merlin and both 0.1.1 and HEAD version of neovim on osx. Installed via homebrew.

**Comment by justinmk** [comment]
Did you `pip install --upgrade neovim` ?

**Comment by mseri** [comment]
Oh gosh, I did a fresh reinstall but it was still using 0.0.27. Upgrading worked. Thank you very much (and sorry for wasting your time like that)
